""" This is a "compiled" version containing only those dlls and functions that are actually used by the application """

from ctypes.wintypes import *
from .types import *

advapi32 = ctypes.windll.advapi32
comctl32 = ctypes.windll.comctl32
gdi32 = ctypes.windll.gdi32
kernel32 = ctypes.windll.kernel32
shell32 = ctypes.windll.shell32
user32 = ctypes.windll.user32
uxtheme = ctypes.windll.uxtheme

advapi32.RegCloseKey.argtypes = (HKEY,)
advapi32.RegCloseKey.restype = LSTATUS
advapi32.RegOpenKeyW.argtypes = (HKEY, LPCWSTR, PHKEY)
advapi32.RegOpenKeyW.restype = LSTATUS
advapi32.RegQueryValueExW.argtypes = (HKEY, LPCWSTR, LPDWORD, LPDWORD, LPVOID, LPDWORD)
advapi32.RegQueryValueExW.restype = LSTATUS
comctl32.ImageList_AddIcon = lambda handle, hicon: comctl32.ImageList_ReplaceIcon(handle, -1, hicon)
comctl32.ImageList_BeginDrag.argtypes = (HANDLE, INT, INT, INT)
comctl32.ImageList_Create.restype = HANDLE
comctl32.ImageList_GetIcon.argtypes = (HANDLE, INT, UINT)
comctl32.ImageList_GetIcon.restype = HICON
comctl32.ImageList_GetIconSize.argtypes = (HANDLE, LPINT, LPINT)
comctl32.ImageList_ReplaceIcon.argtypes = (HANDLE, INT, HICON)
gdi32.AddFontResourceW.argtypes = (LPCWSTR,)
gdi32.CreateBitmap.argtypes = (INT, INT, UINT, UINT, LPVOID)
gdi32.CreateBitmap.restype = HBITMAP
gdi32.CreateCompatibleBitmap.argtypes = (HDC, INT, INT)
gdi32.CreateCompatibleBitmap.restype = HBITMAP
gdi32.CreateCompatibleDC.argtypes = (HDC,)
gdi32.CreateCompatibleDC.restype = HDC
gdi32.CreateDIBSection.argtypes = (HDC, LPVOID, UINT, LPVOID, HANDLE, DWORD)
gdi32.CreateDIBSection.restype = HBITMAP
gdi32.CreateFontW.argtypes = (INT, INT, INT, INT, INT, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, LPCWSTR)
gdi32.CreateFontW.restype = HFONT
gdi32.CreateSolidBrush.argtypes = (COLORREF,)
gdi32.CreateSolidBrush.restype = HBRUSH
gdi32.DeleteDC.argtypes = (HDC,)
gdi32.DeleteObject.argtypes = (HANDLE,)
gdi32.GetDeviceCaps.argtypes = (HDC, INT)
gdi32.GetDIBits.argtypes = (HDC, HBITMAP, UINT, UINT, LPVOID, LPVOID, UINT)
gdi32.GetDIBits.restype = INT
gdi32.GetObjectW.argtypes = (HDC, INT, LPVOID)
gdi32.GetStockObject.restype = HANDLE
gdi32.SelectObject.argtypes = (HDC, HANDLE)
gdi32.SelectObject.restype = HANDLE
gdi32.SetBkColor.argtypes = (HDC, COLORREF)
gdi32.SetBkMode.argtypes = (HDC, INT)
gdi32.SetDIBits.argtypes = (HDC, HBITMAP, UINT, UINT, LPVOID, LPVOID, UINT)
gdi32.SetStretchBltMode.argtypes = (HDC, INT)
gdi32.SetTextColor.argtypes = (HDC, COLORREF)
gdi32.StretchBlt.argtypes = (HDC, INT, INT, INT, INT, HDC, INT, INT, INT, INT, DWORD)
kernel32.CloseHandle.argtypes = (HANDLE,)
kernel32.CreatePipe.argtypes = (LPHANDLE, LPHANDLE, LPVOID, DWORD)
kernel32.CreateProcessW.argtypes = (LPCWSTR, LPWSTR, LPVOID, LPVOID, BOOL, DWORD, LPVOID, LPCWSTR, LPVOID, LPVOID)
kernel32.DuplicateHandle.argtypes = (HANDLE, HANDLE, HANDLE, LPHANDLE, DWORD, BOOL, DWORD)
kernel32.GetCurrentProcess.restype = HANDLE
kernel32.GetExitCodeProcess.argtypes = (HANDLE, LPDWORD)
kernel32.GetModuleHandleW.argtypes = (LPCWSTR,)
kernel32.GetModuleHandleW.restype = HMODULE
kernel32.GlobalLock.argtypes = (HGLOBAL,)
kernel32.GlobalLock.restype = LPVOID
kernel32.GlobalUnlock.argtypes = (HANDLE,)
kernel32.LCIDToLocaleName.argtypes = (INT, LPWSTR, INT, DWORD)
kernel32.LoadLibraryW.restype = HANDLE
kernel32.OpenProcess.argtypes = (DWORD, BOOL, DWORD)
kernel32.OpenProcess.restype = HANDLE
kernel32.PeekNamedPipe.argtypes = (HANDLE, LPVOID, DWORD, LPDWORD, LPDWORD, LPDWORD)
kernel32.QueryFullProcessImageNameW.argtypes = (HANDLE, DWORD, LPWSTR, LPDWORD)
kernel32.ReadFile.argtypes = (HANDLE, LPVOID, DWORD, LPDWORD, LPVOID)
shell32.DragAcceptFiles.argtypes = (HWND, BOOL)
shell32.DragFinish.argtypes = (WPARAM,)
shell32.DragQueryFileW.argtypes = (WPARAM, UINT, LPWSTR, UINT)
shell32.RunFileDlg = shell32[61]
shell32.RunFileDlg.argtypes = (HWND, HANDLE, LPWSTR, LPWSTR, LPWSTR, UINT)
shell32.ShellExecuteW.argtypes = (HWND, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, INT)
shell32.ShellExecuteW.restype = HINSTANCE
shell32.SHGetFileInfoW.argtypes = (LPVOID, DWORD, LPVOID, UINT, UINT)
shell32.SHGetFileInfoW.restype = DWORD_PTR
user32.AppendMenuW.argtypes = (HWND, UINT, UINT_PTR, LPCWSTR)
user32.CheckMenuItem.argtypes = (HMENU, UINT, UINT)
user32.CopyImage.argtypes = (HANDLE, UINT, INT, INT, UINT)
user32.CopyImage.restype = HANDLE
user32.CreateWindowExW.argtypes = (DWORD, LPCWSTR, LPCWSTR, DWORD, INT, INT, INT, INT, HWND, HMENU, HINSTANCE, LPVOID)
user32.DefWindowProcW.argtypes = (HWND, UINT, WPARAM, LPARAM)
user32.DeleteMenu.argtypes = (HMENU, UINT, UINT)
user32.DestroyWindow.argtypes = (HWND,)
user32.DispatchMessageW.argtypes = (LPMSG,)
user32.DrawIconEx.argtypes = (HDC, INT, INT, HICON, INT, INT, UINT, HBRUSH, UINT)
user32.DrawTextW.argtypes = (HANDLE, LPCWSTR, INT, LPRECT, UINT)
user32.FillRect.argtypes = (HANDLE, LPRECT, HBRUSH)
user32.FindWindowExW.argtypes = (HWND, HWND, LPCWSTR, LPCWSTR)
user32.FindWindowExW.restype = HWND
user32.FindWindowW.argtypes = (LPCWSTR, LPCWSTR)
user32.FindWindowW.restype = HWND
user32.FrameRect.argtypes = (HDC, LPRECT, HBRUSH)
user32.GetAsyncKeyState.restype = SHORT
user32.GetClassNameW.argtypes = (HWND, LPWSTR, INT)
user32.GetClientRect.argtypes = (HWND, LPRECT)
user32.GetClipboardData.restype = HANDLE
user32.GetDC.argtypes = (HWND,)
user32.GetDC.restype = HDC
user32.GetDesktopWindow.restype = HANDLE
user32.GetForegroundWindow.restype = HANDLE
user32.GetMenuItemCount.argtypes = (HMENU,)
user32.GetMenuItemInfoW.argtypes = (HMENU, UINT, BOOL, LPVOID)
user32.GetMessageW.argtypes = (LPMSG,HWND,UINT,UINT)
user32.GetParent.argtypes = (HWND,)
user32.GetParent.restype = HWND
user32.GetWindow.argtypes = (HANDLE, UINT)
user32.GetWindowLongPtrA.argtypes = (HWND, LONG_PTR)
user32.GetWindowLongPtrA.restype = ULONG
user32.GetWindowRect.argtypes = (HWND, LPRECT)
user32.GetWindowTextW.argtypes = (HWND, LPWSTR, INT)
user32.GetWindowThreadProcessId.argtypes = (HWND, LPDWORD)
user32.IsWindowVisible.argtypes = (HWND,)
user32.LoadCursorW.argtypes = (HINSTANCE, LPVOID)
user32.LoadIconW.argtypes = (HINSTANCE, LPCWSTR)
user32.LoadIconW.restype = HICON
user32.LoadImageW.argtypes = (HINSTANCE, LPCWSTR, UINT, INT, INT, UINT)
user32.LoadImageW.restype = HANDLE
user32.LoadMenuW.argtypes = (HINSTANCE, LPCWSTR)
user32.LoadMenuW.restype = HMENU
user32.LoadStringW.argtypes = (HINSTANCE, UINT, LPWSTR, INT)
user32.MapWindowPoints.argtypes = (HWND, HWND, LPVOID, UINT)
user32.MessageBoxW.argtypes = (HWND, LPCWSTR, LPCWSTR, UINT)
user32.OpenClipboard.argtypes = (HWND,)
user32.OpenClipboard.restype = BOOL
user32.PostMessageW.argtypes = (HWND, UINT, LPVOID, LPVOID)
user32.PostMessageW.restype = LONG_PTR
user32.PrivateExtractIconsW.argtypes = (LPCWSTR, INT, INT, INT, LPVOID, LPUINT, UINT, UINT)
user32.RegisterHotKey.argtypes = (HWND, INT, UINT, UINT)
user32.ReleaseDC.argtypes = (HWND, HANDLE)
user32.SendMessageW.argtypes = (HWND, UINT, LPVOID, LPVOID)
user32.SendMessageW.restype = LONG_PTR
user32.SetLayeredWindowAttributes.argtypes = (HWND, COLORREF, BYTE, DWORD)
user32.SetParent.argtypes = (HWND, HWND)
user32.SetWindowLongPtrA.argtypes = (HWND, LONG_PTR, ULONG)
user32.SetWindowLongPtrA.restype = LONG
user32.SetWindowLongPtrW.argtypes = (HWND, LONG_PTR, WNDPROC)
user32.SetWindowLongPtrW.restype = WNDPROC
user32.SetWindowPos.argtypes = (HWND, LONG_PTR, INT, INT, INT, INT, UINT)
user32.SetWinEventHook.restype = HANDLE
user32.SystemParametersInfoW.argtypes = (UINT, UINT, LPVOID, UINT)
user32.TrackPopupMenuEx.argtypes = (HANDLE, UINT, INT, INT, HANDLE, LPVOID)
user32.TranslateAcceleratorW.argtypes = (HWND, HACCEL, LPMSG)
user32.TranslateMessage.argtypes = (LPMSG,)
user32.UnregisterHotKey.argtypes = (HWND, INT)
uxtheme.FlushMenuThemes = uxtheme[136]
uxtheme.SetPreferredAppMode = uxtheme[135]
uxtheme.SetWindowTheme.argtypes = (HANDLE, LPCWSTR, LPCWSTR)
