#define IDI_APP 1
#define IDI_START 100
#define IDI_NETWORK 101
#define IDI_USB 102

#define POPUP_MENU_START 1
#define POPUP_MENU_PROGRAMS 2
#define POPUP_MENU_QUICK 3

#define IDB_START 1000
#define IDB_TOOLBAR_QUICK 1001

// Menu IDs
#define IDM_OPEN 1
#define IDM_OPEN_ALL_USERS 2
#define IDM_QUIT 3
#define IDM_DEBUG_TOGGLE_CONSOLE 6

//#define IDM_DEBUG_RESTART 7
//#define IDM_DEBUG_KILL_EXPLORER 8
//#define IDM_DEBUG_REBUILD_ICON_CACHE 9
//
//#define IDM_TOGGLE_LOAD_TASKBAR 10
//#define IDM_TOGGLE_LOAD_DESKTOP 11
//
//#define IDM_TOGGLE_REPLACE_FILEMANAGER 12
//#define IDM_TOGGLE_REPLACE_SHELL 13
//
//#define IDM_TASKBAR_SIZE 15
//#define IDM_TASKBAR_SIZE_SMALL 16
//#define IDM_TASKBAR_SIZE_BIG 17
//
//#define IDM_THEME_AUTO 20
//#define IDM_THEME_DARK 21
//#define IDM_THEME_LIGHT 22
//
//#define IDM_OPEN_QUICK 50
//#define IDM_FIXED_TASKBAR 51
//
//#define IDM_PROGRAMS_OPEN 104
//#define IDM_PROGRAMS_OPEN_ALL_USERS 105
//#define IDM_PROGRAMS_PROPERTIES 106
