#define IDI_APP 1

#define IDI_START_DARK 100
#define IDI_START_LIGHT 101

#define IDI_NETWORK_DARK 102
#define IDI_NETWORK_LIGHT 103

#define IDI_USB_DARK 104
#define IDI_USB_LIGHT 105

#define IDI_BATTERY_DARK 106
#define IDI_BATTERY_LIGHT 107

#define IDI_KEYBOARD_DARK 108
#define IDI_KEYBOARD_LIGHT 1097

#define POPUP_MENU_START 1
#define POPUP_MENU_QUICK 2
#define POPUP_MENU_START_MENU_ITEM 3
#define POPUP_MENU_TASKS 4

#define IDB_START 1000
#define IDB_TOOLBAR_QUICK 1001

#define IDM_QUIT 1
#define IDM_DEBUG_TOGGLE_CONSOLE 2

#define IDM_OPEN_LOCATION 1
#define IDM_OPEN_CMD 2
#define IDM_OPEN_POWERSHELL 3

#define IDM_OPEN_STARTMENU 10
#define IDM_SHOW_RUN_DIALOG 11
#define IDM_RUN_EXPLORER 12
#define IDM_RUN_SEARCH 13
#define IDM_TOGGLE_DESKTOP 14
#define IDM_OPEN_TASKMANAGER 15

#define IDS_SAFELY_REMOVE_HARDWARE 100
#define IDS_BATTERY_STATUS 101
#define IDS_BATTERY_STATUS_FMT 102
#define IDS_BATTERY_TIME_REMAINING_FMT 103
#define IDS_NETWORK_OFFLINE 104
